### ISSUE TITLE
SDL2 "undefined reference to `eglUpdateBufferSettings'" at build

### ISSUE THREAD

**Issue by tailtwo** [steward-fu/miyoo-mini#2]
Hello,

I followed the steps to compile SDL2 as described here : https://steward-fu.github.io/website/handheld/miyoo-mini/parasyte_build_sdl2.htm

At the `make -j` step, I end up with an error which stops me from compiling it.

```bash
ubuntu@ubuntu-2204:~/Documents/sdl2$ make -j
/bin/bash ./build-scripts//updaterev.sh
  LTLINK build/libSDL2.la
build/.libs/SDL_opengles_mmiyoo.o: In function `glCreateContext':
/home/ubuntu/Documents/sdl2/src/video/mmiyoo/SDL_opengles_mmiyoo.c:135: undefined reference to `eglUpdateBufferSettings'
collect2: error: ld returned 1 exit status
make: *** [Makefile:158 : build/libSDL2.la] Erreur 1
```

Am I missing something there? What would be causing this issue?

**Comment by steward-fu** [comment]
Hi,
If you need OpenGL ES as your case, you need copy libEGL.so and libGLESv2.so into the root folder of SDL2 and then build it because of SDL2 need to setup framebuffer pointer intoOpenGL ES library for miyoo mini.
If you don't need any functionality of OpenGL ES, just comment out eglUpdateBufferSettings() and then build it.

**Comment by tailtwo** [comment]
While commenting the line allow me to compile, I am still not able to compile with OpenGL ES support. I added the related armhf version of libEGL.so and libGLESv2.so in the root of the SDL2 folder and also installed the related packages to my OS. I still get the same error message.

**Comment by steward-fu** [comment]
Make sure your libEGL.so is correct, which includes eglUpdateBufferSettings() function.
Try the following command to see whether it is correct or not:
```
$ strings libEGL.so | grep eglUpdate
eglUpdateBufferSettings
eglUpdateBufferSettings
```

Here is the packed zip file I built for your testing:
https://drive.google.com/file/d/1kECqH70QyjpxXkX6_pvB3pG-OioUnOJu/view?usp=sharing

**Comment by tailtwo** [comment]
Thank you, I was able to compile SDL with those libraries.
I have a tangentially related question, after compiling a binary and setting my video/audio drive to `mmiyoo`, I get a weird audio output error. Do you have an idea of what would cause that? In any case, consider this issue fixed.
![image](https://user-images.githubusercontent.com/12949450/186549663-6e124461-dc42-4838-8ade-07c058f15b0a.png)

**Comment by steward-fu** [comment]
Try to change the sample value from 1024 to 768, 2048, 4096.
You can check OpenBOR or PPSSPP I ported to see what kind of value they use in SDL2.
It will be the answer you want.
